server:
  port: 3008

spring:
  security:
    oauth2:
      client:
        provider:
          namoid:
            issuer-uri: ${NAMOID_ISSUER}
        registration:
          namoid:
            client-id: ${NAMOID_CLIENT_ID}
            client-secret: ${NAMOID_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${NAMOID_REDIRECT_URI}
            scope: openid,profile,email
            client-name: NamoID
